import * as  countries from "./countries"
import countriesfr from "./countries-fr.json"
import countriesch from "./countries-ch.json"
export const COUNTRIESDATA = [
  {
    title: "A",
    data: [
      countries.AF,
      countries.AX,
      countries.AL,
      countries.DZ,
      countries.AS,
      countries.AD,
      countries.AO,
      countries.AI,
      countries.AG,
      countries.AR,
      countries.AM,
      countries.AW,
      countries.AU,
      countries.AT,
      countries.AZ,
    ],
  },
  {
    title: "B",
    data: [
      countries.BS,
      countries.BH,
      countries.BD,
      countries.BB,
      countries.BY,
      countries.BE,
      countries.BZ,
      countries.BJ,
      countries.BM,
      countries.BT,
      countries.BO,
      countries.BA,
      countries.BW,
      countries.BR,
      countries.IO,
      countries.BN,
      countries.BG,
      countries.BF,
      countries.BI,
    ],
  },
  {
    title: "C",
    data: [
      countries.KH,
      countries.CM,
      countries.CA,
      countries.CV,
      countries.KY,
      countries.CF,
      countries.TD,
      countries.CL,
      countries.CN,
      countries.CX,
      countries.CC,
      countries.CO,
      countries.KM,
      countries.CG,
      countries.CK,
      countries.CR,
      countries.CI,
      countries.HR,
      countries.CU,
      countries.CY,
      countries.CZ,
    ],
  },
  {
    title: "D",
    data: [countries.DK, countries.DJ, countries.DM, countries.DO],
  },
  {
    title: "E",
    data: [
      countries.EC,
      countries.EG,
      countries.SV,
      countries.GQ,
      countries.ER,
      countries.EE,
      countries.ET,
    ],
  },
  {
    title: "F",
    data: [countries.FK, countries.FO, countries.FJ, countries.FI, countries.FR, countries.PF],
  },
  {
    title: "G",
    data: [
      countries.GA,
      countries.GM,
      countries.GE,
      countries.DE,
      countries.GH,
      countries.GI,
      countries.GR,
      countries.GL,
      countries.GD,
      countries.GU,
      countries.GT,
      countries.GG,
      countries.GN,
      countries.GW,
      countries.GY,
    ],
  },
  {
    title: "H",
    data: [countries.HT, countries.VA, countries.HN, countries.HK, countries.HU],
  },
  {
    title: "I",
    data: [
      countries.IS,
      countries.IN,
      countries.ID,
      countries.IR,
      countries.IQ,
      countries.IE,
      countries.IM,
      countries.IL,
      countries.IT,
    ],
  },
  {
    title: "J",
    data: [countries.JM, countries.JP, countries.JE, countries.JO],
  },
  {
    title: "K",
    data: [
      countries.KZ,
      countries.KE,
      countries.KI,
      countries.KP,
      countries.KR,
      countries.XK,
      countries.KW,
      countries.KG,
    ],
  },
  {
    title: "L",
    data: [
      countries.LA,
      countries.LV,
      countries.LB,
      countries.LS,
      countries.LR,
      countries.LY,
      countries.LI,
      countries.LT,
      countries.LU,
    ],
  },
  {
    title: "M",
    data: [
      countries.MO,
      countries.MK,
      countries.MG,
      countries.MW,
      countries.MY,
      countries.MV,
      countries.ML,
      countries.MT,
      countries.MH,
      countries.MQ,
      countries.MR,
      countries.MU,
      countries.MX,
      countries.FM,
      countries.MD,
      countries.MC,
      countries.MN,
      countries.ME,
      countries.MS,
      countries.MA,
      countries.MZ,
      countries.MM,
    ],
  },
  {
    title: "N",
    data: [
      countries.NA,
      countries.NR,
      countries.NP,
      countries.NL,
      countries.NZ,
      countries.NI,
      countries.NE,
      countries.NG,
      countries.NU,
      countries.NF,
      countries.MP,
      countries.NO,
    ],
  },
  {
    title: "O",
    data: [countries.OM],
  },
  {
    title: "P",
    data: [
      countries.PK,
      countries.PW,
      countries.PS,
      countries.PA,
      countries.PG,
      countries.PY,
      countries.PE,
      countries.PH,
      countries.PN,
      countries.PL,
      countries.PT,
      countries.PR,
    ],
  },
  {
    title: "Q",
    data: [countries.QA],
  },
  {
    title: "R",
    data: [countries.RO, countries.RU, countries.RW],
  },
  {
    title: "S",
    data: [
      countries.KN,
      countries.WS,
      countries.SM,
      countries.ST,
      countries.SA,
      countries.SN,
      countries.RS,
      countries.SC,
      countries.SL,
      countries.SG,
      countries.SK,
      countries.SI,
      countries.SB,
      countries.SO,
      countries.ZA,
      countries.SS,
      countries.ES,
      countries.LK,
      countries.SD,
      countries.SR,
      countries.SZ,
      countries.SE,
      countries.CH,
      countries.SY,
    ],
  },
  {
    title: "T",
    data: [
      countries.TW,
      countries.TJ,
      countries.TZ,
      countries.TH,
      countries.TL,
      countries.TG,
      countries.TK,
      countries.TO,
      countries.TT,
      countries.TN,
      countries.TR,
      countries.TM,
      countries.TC,
      countries.TV,
    ],
  },
  {
    title: "U",
    data: [
      countries.UG,
      countries.UA,
      countries.AE,
      countries.GB,
      countries.US,
      countries.UY,
      countries.UZ,
    ],
  },
  {
    title: "V",
    data: [countries.VU, countries.VE, countries.VN, countries.VG],
  },
  {
    title: "Y",
    data: [countries.YE],
  },
  {
    title: "Z",
    data: [countries.ZM, countries.ZW],
  },
]
export const COUNTRIESDATAFR = [
  {
    title: "A",
    data: [
      countriesfr.AF,
      countriesfr.AX,
      countriesfr.AL,
      countriesfr.DZ,
      countriesfr.AS,
      countriesfr.AD,
      countriesfr.AO,
      countriesfr.AI,
      countriesfr.AG,
      countriesfr.AR,
      countriesfr.AM,
      countriesfr.AW,
      countriesfr.AU,
      countriesfr.AT,
      countriesfr.AZ,
    ],
  },
  {
    title: "B",
    data: [
      countriesfr.BS,
      countriesfr.BH,
      countriesfr.BD,
      countriesfr.BB,
      countriesfr.BY,
      countriesfr.BE,
      countriesfr.BZ,
      countriesfr.BJ,
      countriesfr.BM,
      countriesfr.BT,
      countriesfr.BO,
      countriesfr.BA,
      countriesfr.BW,
      countriesfr.BR,
      countriesfr.IO,
      countriesfr.BN,
      countriesfr.BG,
      countriesfr.BF,
      countriesfr.BI,
    ],
  },
  {
    title: "C",
    data: [
      countriesfr.KH,
      countriesfr.CM,
      countriesfr.CA,
      countriesfr.CV,
      countriesfr.KY,
      countriesfr.CF,
      countriesfr.TD,
      countriesfr.CL,
      countriesfr.CN,
      countriesfr.CX,
      countriesfr.CC,
      countriesfr.CO,
      countriesfr.KM,
      countriesfr.CG,
      countriesfr.CK,
      countriesfr.CR,
      countriesfr.CI,
      countriesfr.HR,
      countriesfr.CU,
      countriesfr.CY,
      countriesfr.CZ,
    ],
  },
  {
    title: "D",
    data: [countriesfr.DK, countriesfr.DJ, countriesfr.DM, countriesfr.DO],
  },
  {
    title: "E",
    data: [
      countriesfr.EC,
      countriesfr.EG,
      countriesfr.SV,
      countriesfr.GQ,
      countriesfr.ER,
      countriesfr.EE,
      countriesfr.ET,
    ],
  },
  {
    title: "F",
    data: [
      countriesfr.FK,
      countriesfr.FO,
      countriesfr.FJ,
      countriesfr.FI,
      countriesfr.FR,
      countriesfr.PF,
    ],
  },
  {
    title: "G",
    data: [
      countriesfr.GA,
      countriesfr.GM,
      countriesfr.GE,
      countriesfr.DE,
      countriesfr.GH,
      countriesfr.GI,
      countriesfr.GR,
      countriesfr.GL,
      countriesfr.GD,
      countriesfr.GU,
      countriesfr.GT,
      countriesfr.GG,
      countriesfr.GN,
      countriesfr.GW,
      countriesfr.GY,
    ],
  },
  {
    title: "H",
    data: [countriesfr.HT, countriesfr.VA, countriesfr.HN, countriesfr.HK, countriesfr.HU],
  },
  {
    title: "I",
    data: [
      countriesfr.IS,
      countriesfr.IN,
      countriesfr.ID,
      countriesfr.IR,
      countriesfr.IQ,
      countriesfr.IE,
      countriesfr.IM,
      countriesfr.IL,
      countriesfr.IT,
    ],
  },
  {
    title: "J",
    data: [countriesfr.JM, countriesfr.JP, countriesfr.JE, countriesfr.JO],
  },
  {
    title: "K",
    data: [
      countriesfr.KZ,
      countriesfr.KE,
      countriesfr.KI,
      countriesfr.KP,
      countriesfr.KR,
      countriesfr.XK,
      countriesfr.KW,
      countriesfr.KG,
    ],
  },
  {
    title: "L",
    data: [
      countriesfr.LA,
      countriesfr.LV,
      countriesfr.LB,
      countriesfr.LS,
      countriesfr.LR,
      countriesfr.LY,
      countriesfr.LI,
      countriesfr.LT,
      countriesfr.LU,
    ],
  },
  {
    title: "M",
    data: [
      countriesfr.MO,
      countriesfr.MK,
      countriesfr.MG,
      countriesfr.MW,
      countriesfr.MY,
      countriesfr.MV,
      countriesfr.ML,
      countriesfr.MT,
      countriesfr.MH,
      countriesfr.MQ,
      countriesfr.MR,
      countriesfr.MU,
      countriesfr.MX,
      countriesfr.FM,
      countriesfr.MD,
      countriesfr.MC,
      countriesfr.MN,
      countriesfr.ME,
      countriesfr.MS,
      countriesfr.MA,
      countriesfr.MZ,
      countriesfr.MM,
    ],
  },
  {
    title: "N",
    data: [
      countriesfr.NA,
      countriesfr.NR,
      countriesfr.NP,
      countriesfr.NL,
      countriesfr.NZ,
      countriesfr.NI,
      countriesfr.NE,
      countriesfr.NG,
      countriesfr.NU,
      countriesfr.NF,
      countriesfr.MP,
      countriesfr.NO,
    ],
  },
  {
    title: "O",
    data: [countriesfr.OM],
  },
  {
    title: "P",
    data: [
      countriesfr.PK,
      countriesfr.PW,
      countriesfr.PS,
      countriesfr.PA,
      countriesfr.PG,
      countriesfr.PY,
      countriesfr.PE,
      countriesfr.PH,
      countriesfr.PN,
      countriesfr.PL,
      countriesfr.PT,
      countriesfr.PR,
    ],
  },
  {
    title: "Q",
    data: [countriesfr.QA],
  },
  {
    title: "R",
    data: [countriesfr.RO, countriesfr.RU, countriesfr.RW],
  },
  {
    title: "S",
    data: [
      countriesfr.KN,
      countriesfr.WS,
      countriesfr.SM,
      countriesfr.ST,
      countriesfr.SA,
      countriesfr.SN,
      countriesfr.RS,
      countriesfr.SC,
      countriesfr.SL,
      countriesfr.SG,
      countriesfr.SK,
      countriesfr.SI,
      countriesfr.SB,
      countriesfr.SO,
      countriesfr.ZA,
      countriesfr.SS,
      countriesfr.ES,
      countriesfr.LK,
      countriesfr.SD,
      countriesfr.SR,
      countriesfr.SZ,
      countriesfr.SE,
      countriesfr.CH,
      countriesfr.SY,
    ],
  },
  {
    title: "T",
    data: [
      countriesfr.TW,
      countriesfr.TJ,
      countriesfr.TZ,
      countriesfr.TH,
      countriesfr.TL,
      countriesfr.TG,
      countriesfr.TK,
      countriesfr.TO,
      countriesfr.TT,
      countriesfr.TN,
      countriesfr.TR,
      countriesfr.TM,
      countriesfr.TC,
      countriesfr.TV,
    ],
  },
  {
    title: "U",
    data: [
      countriesfr.UG,
      countriesfr.UA,
      countriesfr.AE,
      countriesfr.GB,
      countriesfr.US,
      countriesfr.UY,
      countriesfr.UZ,
    ],
  },
  {
    title: "V",
    data: [countriesfr.VU, countriesfr.VE, countriesfr.VN, countriesfr.VG],
  },
  {
    title: "Y",
    data: [countriesfr.YE],
  },
  {
    title: "Z",
    data: [countriesfr.ZM, countriesfr.ZW],
  },
]

export const COUNTRIESDATACH = [
  {
    title: "A",
    data: [
      countriesch.AF,
      countriesch.AX,
      countriesch.AL,
      countriesch.DZ,
      countriesch.AS,
      countriesch.AD,
      countriesch.AO,
      countriesch.AI,
      countriesch.AG,
      countriesch.AR,
      countriesch.AM,
      countriesch.AW,
      countriesch.AU,
      countriesch.AT,
      countriesch.AZ,
    ],
  },
  {
    title: "B",
    data: [
      countriesch.BS,
      countriesch.BH,
      countriesch.BD,
      countriesch.BB,
      countriesch.BY,
      countriesch.BE,
      countriesch.BZ,
      countriesch.BJ,
      countriesch.BM,
      countriesch.BT,
      countriesch.BO,
      countriesch.BA,
      countriesch.BW,
      countriesch.BR,
      countriesch.IO,
      countriesch.BN,
      countriesch.BG,
      countriesch.BF,
      countriesch.BI,
    ],
  },
  {
    title: "C",
    data: [
      countriesch.KH,
      countriesch.CM,
      countriesch.CA,
      countriesch.CV,
      countriesch.KY,
      countriesch.CF,
      countriesch.TD,
      countriesch.CL,
      countriesch.CN,
      countriesch.CX,
      countriesch.CC,
      countriesch.CO,
      countriesch.KM,
      countriesch.CG,
      countriesch.CK,
      countriesch.CR,
      countriesch.CI,
      countriesch.HR,
      countriesch.CU,
      countriesch.CY,
      countriesch.CZ,
    ],
  },
  {
    title: "D",
    data: [countriesch.DK, countriesch.DJ, countriesch.DM, countriesch.DO],
  },
  {
    title: "E",
    data: [
      countriesch.EC,
      countriesch.EG,
      countriesch.SV,
      countriesch.GQ,
      countriesch.ER,
      countriesch.EE,
      countriesch.ET,
    ],
  },
  {
    title: "F",
    data: [
      countriesch.FK,
      countriesch.FO,
      countriesch.FJ,
      countriesch.FI,
      countriesch.FR,
      countriesch.PF,
    ],
  },
  {
    title: "G",
    data: [
      countriesch.GA,
      countriesch.GM,
      countriesch.GE,
      countriesch.DE,
      countriesch.GH,
      countriesch.GI,
      countriesch.GR,
      countriesch.GL,
      countriesch.GD,
      countriesch.GU,
      countriesch.GT,
      countriesch.GG,
      countriesch.GN,
      countriesch.GW,
      countriesch.GY,
    ],
  },
  {
    title: "H",
    data: [countriesch.HT, countriesch.VA, countriesch.HN, countriesch.HK, countriesch.HU],
  },
  {
    title: "I",
    data: [
      countriesch.IS,
      countriesch.IN,
      countriesch.ID,
      countriesch.IR,
      countriesch.IQ,
      countriesch.IE,
      countriesch.IM,
      countriesch.IL,
      countriesch.IT,
    ],
  },
  {
    title: "J",
    data: [countriesch.JM, countriesch.JP, countriesch.JE, countriesch.JO],
  },
  {
    title: "K",
    data: [
      countriesch.KZ,
      countriesch.KE,
      countriesch.KI,
      countriesch.KP,
      countriesch.KR,
      countriesch.XK,
      countriesch.KW,
      countriesch.KG,
    ],
  },
  {
    title: "L",
    data: [
      countriesch.LA,
      countriesch.LV,
      countriesch.LB,
      countriesch.LS,
      countriesch.LR,
      countriesch.LY,
      countriesch.LI,
      countriesch.LT,
      countriesch.LU,
    ],
  },
  {
    title: "M",
    data: [
      countriesch.MO,
      countriesch.MK,
      countriesch.MG,
      countriesch.MW,
      countriesch.MY,
      countriesch.MV,
      countriesch.ML,
      countriesch.MT,
      countriesch.MH,
      countriesch.MQ,
      countriesch.MR,
      countriesch.MU,
      countriesch.MX,
      countriesch.FM,
      countriesch.MD,
      countriesch.MC,
      countriesch.MN,
      countriesch.ME,
      countriesch.MS,
      countriesch.MA,
      countriesch.MZ,
      countriesch.MM,
    ],
  },
  {
    title: "N",
    data: [
      countriesch.NA,
      countriesch.NR,
      countriesch.NP,
      countriesch.NL,
      countriesch.NZ,
      countriesch.NI,
      countriesch.NE,
      countriesch.NG,
      countriesch.NU,
      countriesch.NF,
      countriesch.MP,
      countriesch.NO,
    ],
  },
  {
    title: "O",
    data: [countriesch.OM],
  },
  {
    title: "P",
    data: [
      countriesch.PK,
      countriesch.PW,
      countriesch.PS,
      countriesch.PA,
      countriesch.PG,
      countriesch.PY,
      countriesch.PE,
      countriesch.PH,
      countriesch.PN,
      countriesch.PL,
      countriesch.PT,
      countriesch.PR,
    ],
  },
  {
    title: "Q",
    data: [countriesch.QA],
  },
  {
    title: "R",
    data: [countriesch.RO, countriesch.RU, countriesch.RW],
  },
  {
    title: "S",
    data: [
      countriesch.KN,
      countriesch.WS,
      countriesch.SM,
      countriesch.ST,
      countriesch.SA,
      countriesch.SN,
      countriesch.RS,
      countriesch.SC,
      countriesch.SL,
      countriesch.SG,
      countriesch.SK,
      countriesch.SI,
      countriesch.SB,
      countriesch.SO,
      countriesch.ZA,
      countriesch.SS,
      countriesch.ES,
      countriesch.LK,
      countriesch.SD,
      countriesch.SR,
      countriesch.SZ,
      countriesch.SE,
      countriesch.CH,
      countriesch.SY,
    ],
  },
  {
    title: "T",
    data: [
      countriesch.TW,
      countriesch.TJ,
      countriesch.TZ,
      countriesch.TH,
      countriesch.TL,
      countriesch.TG,
      countriesch.TK,
      countriesch.TO,
      countriesch.TT,
      countriesch.TN,
      countriesch.TR,
      countriesch.TM,
      countriesch.TC,
      countriesch.TV,
    ],
  },
  {
    title: "U",
    data: [
      countriesch.UG,
      countriesch.UA,
      countriesch.AE,
      countriesch.GB,
      countriesch.US,
      countriesch.UY,
      countriesch.UZ,
    ],
  },
  {
    title: "V",
    data: [countriesch.VU, countriesch.VE, countriesch.VN, countriesch.VG],
  },
  {
    title: "Y",
    data: [countriesch.YE],
  },
  {
    title: "Z",
    data: [countriesch.ZM, countriesch.ZW],
  },
]
